package com.intellijeep.db;

import com.intellijeep.config.ConnectionUtil;
import com.intellijeep.model.User;
import com.intellijeep.util.IntelliJeepArrayList;
import com.intellijeep.util.QueryCreationUtility;

import java.sql.*;

public class UserDao implements GenericDao<User> {

    private QueryCreationUtility queryCreationUtility;
    /**
     * Singleton design pattern
     */
    private static UserDao instance;

    private UserDao(){}

    static UserDao getInstance() {
        if(instance == null) {
            instance = new UserDao();
        }

        return instance;
    }

    /*
    In save function, rather than return number of updated rows, see if it can return
    the serial userID created.

    Create the session from ConnectionUtil
    Create prepared statement for inserting new user
    Return user's id
     */

    @Override
    public int save(User user) {

        int key = -1;
        //All fields merged into User table bc all functionally dependent on userID
        String query = "insert into app_user (username,password, type, first_name, last_name, email, phone_number, street_address, city, state, zipcode) values(?,?,?,?,?,?,?,?,?,?,?)";
        try (Connection conn = ConnectionUtil.getConnection("dev")) {
            PreparedStatement ps = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            //ps = conn.prepareStatement(queryCreationUtility.createUserInsertionQuery(user,ps), Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, user.getAccountData().getUsername());
            ps.setString(2, user.getAccountData().getPassword());
            ps.setInt(3, user.getAccountData().getAccountType().convert());
            ps.setString(4, user.getPersonalInfo().getFirstName());
            ps.setString(5, user.getPersonalInfo().getLastName());
            ps.setString(6, user.getPersonalInfo().getEmail());
            ps.setString(7, user.getPersonalInfo().getPhoneNumber());
            ps.setString(8, user.getLocationData().getStreetAddress());
            ps.setString(9, user.getLocationData().getCity());
            ps.setString(10, user.getLocationData().getState());
            ps.setString(11, user.getLocationData().getZipCode());

            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();
            if(rs.next()) {
                key = rs.getInt(1); //Column index 1 is the autogenerated id
            }
            ps.close();
            return key;

        } catch (SQLException throwables) {
            throwables.printStackTrace();
            return key;
        }
    }


    @Override
    public User getByID(Integer id) {
        return null;
    }

    @Override
    public IntelliJeepArrayList<User> getAll() {
        return null;
    }

    @Override
    public Boolean remove(Integer id) {
        return null;
    }

    @Override
    public Boolean update(User user) {
        return null;
    }

    @Override
    public int updateAll(IntelliJeepArrayList<User> collection) {
        return 0;
    }
}
